name: win-build

on:
  push:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:
    inputs:
      branch:
        description: Chromium Branch Number to Build
        type: string
        required: true

jobs:
  winbuild:
    name: Compile
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x86, x64, arm64]
        target-os: [win, winuwp]
        exclude:
          - target-cpu: arm64
            target-os: winuwp
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    defaults:
      run:
        shell: cmd
    steps:
    - name: Download Windows SDK Setup 10.0.26100
      run: curl -Lfo winsdksetup.exe https://go.microsoft.com/fwlink/?linkid=2286561
    - name: Install Windows SDK 10.0.26100 and Debugging Tools
      id: windbg
      run: |
        setlocal enabledelayedexpansion
        start /WAIT %CD%\winsdksetup.exe /features OptionId.WindowsDesktopDebuggers OptionId.DesktopCPPx86 OptionId.DesktopCPPx64 OptionId.DesktopCPParm64 OptionId.UWPCPP OptionId.UWPManaged /q /norestart /log %CD%\log.txt
        echo ERRORLEVEL=!ERRORLEVEL! >> %GITHUB_OUTPUT%
    - name: Print Log
      if: always()
      run: |
        type log.txt
        exit /b ${{ steps.windbg.outputs.ERRORLEVEL }}
    - name: Download Depot Tools
      shell: python
      run: |
        import os
        
        for i in range(250):
            if os.system("git clone --filter=tree:0 https://chromium.googlesource.com/chromium/tools/depot_tools depot_tools") == 0:
                raise SystemExit(0)
        
        raise Exception("cloning depot tools failed")
    - name: Initialize Depot Tools
      working-directory: depot_tools
      run: |
        gclient
        exit /b 0
    - name: Prepend Depot Tools to PATH
      working-directory: depot_tools
      run: |
        set /p="%CD%" < nul >> %GITHUB_PATH%
        exit /b 0
    - name: Create ANGLE Directory
      run: mkdir angle
    - name: Fetch ANGLE
      working-directory: angle
      run: fetch angle
    - name: Checkout ANGLE Branch
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.branch != 'main' }}
      working-directory: angle
      run: git checkout origin/chromium/${{ inputs.branch }}
    - name: Sync ANGLE
      working-directory: angle
      run: gclient sync
    - name: Configure ANGLE
      env:
        ANGLE_TARGET_CPU: ${{ matrix.target-cpu }}
        ANGLE_TARGET_OS: ${{ matrix.target-os }}
      working-directory: angle
      run: gn gen out/Hello --args="target_cpu=\"%ANGLE_TARGET_CPU%\" target_os=\"%ANGLE_TARGET_OS%\" is_debug=false is_component_build=false angle_enable_d3d9=false angle_enable_gl=false"
    - name: Build
      working-directory: angle
      run: autoninja -C out/Hello libEGL libGLESv2
    - name: Artifact Preparation
      run: |
        mkdir output
        copy angle\out\Hello\libEGL.dll output\libEGL.dll
        copy angle\out\Hello\libGLESv2.dll output\libGLESv2.dll
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: angle-${{ matrix.target-cpu }}-${{ matrix.target-os }}
        path: output/
  release:
    name: Upload
    runs-on: ubuntu-latest
    needs: winbuild
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'master') }}
    steps:
    - name: Install Zip
      run: sudo apt-get install --assume-yes zip curl libfuse2
    - name: Determinator
      id: kind
      env:
        BUILD_BRANCH: ${{ inputs.branch || 'main' }}
      run: |
        set -e
        if [ "$BUILD_BRANCH" == "main" ]; then
            echo "type=prerelease" >> $GITHUB_OUTPUT
            echo "name=Continuous Build" >> $GITHUB_OUTPUT
            echo "tag=continuous" >> $GITHUB_OUTPUT
        else
            echo "type=stable" >> $GITHUB_OUTPUT
            echo "name=ANGLE Branch $BUILD_BRANCH" >> $GITHUB_OUTPUT
            echo "tag=cr_$BUILD_BRANCH" >> $GITHUB_OUTPUT
        fi
    - name: Download pyuploadtool
      run: curl -LO https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage && chmod +x pyuploadtool-x86_64.AppImage
    - name: Download Artifacts
      uses: actions/download-artifact@v4
    - name: List All Files
      run: ls -alFR
    - name: Zip x86 Binaries
      run: zip -j angle-win-x86.zip angle-x86-win/*
    - name: Zip x64 Binaries
      run: zip -j angle-win-x64.zip angle-x64-win/*
    - name: Zip ARM64 Binaries
      run: zip -j angle-win-arm64.zip angle-arm64-win/*
    - name: Zip x86 Binaries (UWP)
      run: zip -j angle-winuwp-x86.zip angle-x86-winuwp/*
    - name: Zip x64 Binaries (UWP)
      run: zip -j angle-winuwp-x64.zip angle-x64-winuwp/*
    #- name: Zip ARM64 Binaries (UWP)
    #  run: zip -j angle-winuwp-arm64.zip angle-arm64-winuwp/*
    - name: Upload to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTINUOUS_RELEASE_TYPE: ${{ steps.kind.outputs.type }}
        GITHUB_CONTINUOUS_RELEASE_NAME: ${{ steps.kind.outputs.name }}
        GITHUB_CONTINUOUS_RELEASE_TAG: ${{ steps.kind.outputs.tag }}
      run: ./pyuploadtool-x86_64.AppImage angle-win*-*.zip
